config/routes.rb
MakerBistro::Application.routes.draw do
    root 'menu_items#index'

    resources :menu_items do
      resources :ingredients
    end

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :ingredient_menus
  has_many :menu_items, through: :ingredient_menus
end

app/models/ingredient_menu.rb
class IngredientMenu < ActiveRecord::Base
  belongs_to :menu_item
  belongs_to :ingredient
end

app/models/ingredient_menu_item.rb
class IngredientMenuItem < ActiveRecord::Base
  belongs_to :menuitem
  belongs_to :ingredient
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  has_many :ingredient_menus
  has_many :ingredients, through: :ingredient_menus
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController


  def index
  end

  def new
    @menu_item = MenuItem.find(params[:menu_item_id])
    @ingredient = @menu_item.ingredients.new
  end

  def create

    @menu_item = MenuItem.find(params[:menu_item_id])
    @ingredients = @menu_item.ingredients.create(ingredients_params)
    # @ingredients.save
    redirect_to root_path
  end

  private

  def ingredients_params
    params.require(:ingredient).permit(:name)
  end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController

  def index
    @menu_items = MenuItem.all
  end

  def show
    @menu_item = MenuItem.find(params[:id])
  end

  def new
    @menu_item = MenuItem.new
  end

  def create
    @menu_item = MenuItem.create(menu_item_params)
    # @menu.save
    redirect_to root_path
  end

  def edit
    @menu_item = MenuItem.find(params[:id])
  end

  def update
    @menu_item = MenuItem.find(params[:id])
  end

  def destroy
    @menu_item = MenuItem.find(params[:id])
  end


  private

  def menu_item_params
    params.require(:menu_item).permit(:name, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/ingredients/create.html.erb
<h1>Ingredients#create</h1>
<p>Find me in app/views/ingredients/create.html.erb</p>

app/views/ingredients/edit.html.erb
<h1>Ingredients#edit</h1>
<p>Find me in app/views/ingredients/edit.html.erb</p>

app/views/ingredients/index.html.erb
<% @ingredients.each do |ingredient| %>
  <%= "#{ingredient.name}" %> <br>
  <% end %>

app/views/ingredients/new.html.erb
<%= form_for([@menu_item, @ingredient], url: menu_item_ingredients_path) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br />
  <%= submit_tag("submit") %>
<% end %>

app/views/ingredients/update.html.erb
<h1>Ingredients#update</h1>
<p>Find me in app/views/ingredients/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MakerBistro</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1>The MakerBistro</h1>

<%= yield %>

</body>
</html>

app/views/menu_items/create.html.erb
<h1>MenuItems#create</h1>
<p>Find me in app/views/menu_items/create.html.erb</p>

app/views/menu_items/edit.html.erb
<h1>MenuItems#edit</h1>
<p>Find me in app/views/menu_items/edit.html.erb</p>

app/views/menu_items/index.html.erb
<h2>Menu Items</h2>
<% @menu_items.each do |menu_item| %>
  Name: <%= menu_item.name %>,
  Price: <%= menu_item.price %>,
  Ingredients: <% menu_item.ingredients.each do |i| %>
    <%= i.name %>
  <% end %>
  (<%= link_to 'Add ingredient', new_menu_item_ingredient_url(menu_item.id) %>)
  (<%= link_to 'Edit', edit_menu_item_url(menu_item) %>)
  <%= link_to 'Delete', menu_item, method: :delete, data: { confirm: 'Are you sure?' } %><br/>
<% end %>

<br />
<%= link_to 'Add a new menu item', new_menu_item_path %><br/>

app/views/menu_items/new.html.erb
<%= form_for(@menu_item) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br />
  <%= f.label :price %>
  <%= f.text_field :price %><br />
  <%= submit_tag("submit") %>
<% end %>

app/views/menu_items/show.html.erb
<h3><%=  @menu_item.name %> &nbsp; $<%= @menu_item.price %>.00 </h3>
<h4>Ingredients:</h4>
<ul><% @menu_item.ingredients.each do |ingredient| %>
  <li>  <%= "#{ingredient.name}" %> </li>
<% end %>
  </ul>

app/views/menu_items/update.html.erb
<h1>MenuItems#update</h1>
<p>Find me in app/views/menu_items/update.html.erb</p>